### ISSUE TITLE
wrong fetching of ability modifier in CalcAttackDmgHit (?)

### ISSUE THREAD

**Issue by SimonDeRidder** [morepurplemorebetter/MPMBs-Character-Record-Sheet#124]
https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/06e0d447f870e3a4e897d83463d845fdc27fd175/_functions/Functions2.js#L5834

The above line seems designed to fetch the relevant ability modifier, but `fields.Mod` is set to `What(fldBase + "Mod")`, so would fetch the value of e.g. the `Str` field, and not the `Str Mod` field. (Unless I'm missing something)

**Comment by morepurplemorebetter** [comment]
Did you encounter a scenario where the ability modifier is not correctly applied to attack or damage?
I understand that it is confusing. This function is the I-don't-know-how-many version of the attack automation process, which was the first thing I automated in this sheet. I never changed how the fields work for backwards compatibility.

The function that you are referring to leverages the export value of a dropdown box in the AcroForm PDF (i.e. field.value). That export value is "Str Mod" for its second entry "Str". That's why it works.

**Comment by SimonDeRidder** [comment]
Ah, I see. I was just confused when reading the function, but I didn't realise the export value was different from the displayed entry. Apologies for the disruption.
