### ISSUE TITLE
Styling issue on the new class JS window

### ISSUE THREAD

**Issue by erickrause** [morepurplemorebetter/MPMBs-Character-Record-Sheet#14]
Seems I'm getting some styling issues with the new pop up.  I was able to work around them by clicking into a field I could hit and tabbing to the correct field to change it.

![javascript window 2017-04-25 20-38-50](https://cloud.githubusercontent.com/assets/118276/25417620/9c3571b6-2a02-11e7-8ad0-c8b3a3e577ba.png)

Adobe Acrobat Reader DC
Version 2017.009.20044

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this! Somebody on my Patreon beat you to it. The issue is happening because you are on a Mac and because there are tiny differences between the Windows and Mac version of Adobe Acrobat. I don't own a Mac, so I have no way of testing the sheet for it. Feedback like this is greatly appreciated!

With the help of the reporter on Patreon, I was able to fix the issue, I think. I just need somebody with a Mac to confirm that there no longer is any overlap and that all rows are the same size.

Would you be so kind to take a look at this Test-Version of the sheet and send back a screenshot of the dialogue with a couple of rows? https://www.dropbox.com/s/2pyhjte4kle6sjh/MPMB%20CRS%20%28v12.97-test%29%20%5BPF-Redesign%5D.pdf?dl=0

**Comment by erickrause** [comment]
Looks good to me.  
![javascript window 2017-04-26 14-51-31](https://cloud.githubusercontent.com/assets/118276/25456352/e47dfb4a-2a8f-11e7-9c58-3b543132a0bf.png)

**Comment by morepurplemorebetter** [comment]
Could you please add a couple of rows and add some text in them to see if all rows are equal height?

**Comment by erickrause** [comment]
![javascript window 2017-04-26 15-07-26](https://cloud.githubusercontent.com/assets/118276/25457044/1b8dc94c-2a92-11e7-8960-32a48875105a.png)
Looks like it started to run out of room below where it was showing the text.  But the rows looked good.

**Comment by morepurplemorebetter** [comment]
Thank you very much, it does indeed look like every thing is working!

The text being cut-off is a bit of a concious decision on my part. On the one hand it is the practical reason that having a bigger field for the total text is not necessary for most classes, and on the other hand it corresponds well with the limited amount of space you have on the sheet to put your class names.

Anyway, [here is the fix](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_functions/ClassSelection.js#L107) if you are interested.
