### ISSUE TITLE
Subrace list

### ISSUE THREAD

**Issue by magnusprime27** [morepurplemorebetter/MPMBs-Character-Record-Sheet#28]
I'm working on a race, Serafu
Is mechanically just like the dragon born and its subraces black bronze ect.
Going off  the homebrew syntax file I don't understand his to end it.
Its a var list cuz its a lot of variable races. But in your complete file vs the homebrew syntax doesn't make sence

**Comment by magnusprime27** [comment]
Compared to the variant human, tiefling and half elf types, the dragon born black bronze etc, don't have source or trait entries like the others do is flthis right?

**Comment by morepurplemorebetter** [comment]
Follow the homebrew syntax files for adding your own material. The files in the [_variables](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/tree/master/_variables) folder are not te be used as examples for the complete syntax, because there is a difference between adding the content initially and later. Use the syntax files for adding content using the import.

For racial variants, anything you define will overwrite the value in the race entry. So if you don't enter a source for the racial variant, it will use the source of the race.
