### ISSUE TITLE
Sorcerer Draconic Bloodline Feat

### ISSUE THREAD

**Issue by hsnopi** [morepurplemorebetter/MPMBs-Character-Record-Sheet#29]
Hello,
Just FYI,
I have a level 4 dwarf sorcerer/Draconic Bloodline. For some reason the feat 
 Bronze Dragon Ancestor (Draconic Bloodline 1, PHB 102)
   I have draconic ancestry with bronze dragons, which are affiliated with lightning dmg
   When interacting with dragons, if I can add my proficiency bonus, I can double it
Is being auto inserted at level 4. I believe it is supposed to be level 6. I tried to find the code to see if I could help but couldn't find it.
I'm using the All Official Content script.

What can I do to help fix this? or where is the class? I found wild mage and storm sorcerer but not that one.
Thanks
Hsnopi

**Comment by morepurplemorebetter** [comment]
I wrote a long reply, see below, but I'm guessing I can answer this really shortly: **You are confusing the 1st level class feature "Dragon Ancestry" with the 6th level class feature "Elemental Affinity".**

The long reply stems from the confusing use of 'feat' for a class feature and the fact that you are posting this to a GitHub which has nothing to do with the content you are talking about.

First of all, the text you provided is for the 1st level class features of a Sorcerer (Draconic Bloodline), called "Dragon Ancestor", but you say it is appearing as a feat. Did you mean 'feature' instead of feat?

Secondly, the Draconic Bloodline is not SRD content and thus no longer part of this GitHub.

Thirdly, you are not giving any information on what version of the sheets you are using, making it very hard to track down any issues.

You refer to an "All Official Content" script, which, I'm guessing, is taken from a certain subreddit where people are sharing files under that name. Please know that that subreddit is not linked to this GitHub, but to another. Also, they are distributing copyrighted content without a license, so I can't condone their actions!

I would recommend contacting whomever you got the script from to notify them about the issues you are having. I would also recommend describing your issues better or perhaps giving a copy of the pdf you are finding these errors with, because I doubt that anybody will find any issue with a 4th level Draconic Bloodline sorcerer having its 1st level ability be visible. Note that "Draconic Bloodline 1" refers to it being gained at level 1 from the subclass "Draconic Bloodline".

**Comment by hsnopi** [comment]
My apologies for not being specific enough.  I was just trying to help. Thanks for the reply. I'll dig into it. 
thanks,
