### ISSUE TITLE
REQUEST: Option to suppress Javascript window toolbar on startup

### ISSUE THREAD

**Issue by aga9** [morepurplemorebetter/MPMBs-Character-Record-Sheet#40]
As title: an option to NOT pop out the Javascript Window toolbar by default.

The toolbar is only useful for the initial setup of the page, and occasionally thereafter. It's a bit of a nuisance to have to click it away every time.

**Comment by morepurplemorebetter** [comment]
This is not so easy to implement, as it would require some kind of setting to be remembered by the sheet, which requires a field addition and a dedicated menu for it.

Because I feel this is not an essential feature, I'll put it up for a vote on my Patreon when next opportunity arises for adding a 'minor feature'. If voted for, I'll implement it. For now, I'm closing this request.

In the meantime, you can add some custom code to modify the startup function to never make the toolbar:
`if (MakeButtons.toString().indexOf("function ()") === -1) {
	eval(MakeButtons.toString().replace("function MakeButtons() {", "MakeButtons = function() { if(!event.target.name) return;"));
};`
