### ISSUE TITLE
REQUEST: Consolidate customisation options

### ISSUE THREAD

**Issue by aga9** [morepurplemorebetter/MPMBs-Character-Record-Sheet#41]
While most customisation options are accessible from function bookmarks, there remains a few that can only be set within the sheet. It'd be great if they're all also accessible from the bookmarks.

Some of these settings (probably non-exhaustive) include:

- Set the skill list to sort by ability or alphabetically
- Enable the "Attuned Magical Item" section in the equipment list
- Set max HP automation mode (fixed, max, etc.)
- Set boxes to be included in carry weight calculation
- Show a second Ability save DC
- Set companions to show portrait/equipment boxes (by default)

**Comment by morepurplemorebetter** [comment]
Thank you for these suggestions. I like the idea of making the "Set Page Layout" menu more comprehensive. I will see which of the ones you suggest I can add. If you think of any more, please share :)

I won't be able to add an option to change the companion pages though, because you can only change active pages, not the default.

**Comment by morepurplemorebetter** [comment]
I have now added a lot of things to the "Set Page Layout" menu, [see this commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/3e5da7d0dd7fb4728e273727030e34dc0936add4). As always, these changes will be available from the next version onwards :)
