### ISSUE TITLE
Duplicate UA spells in complete spell sheets

### ISSUE THREAD

**Issue by BPrystnk** [morepurplemorebetter/MPMBs-Character-Record-Sheet#43]
I'm unsure whether this has been reported or not but I noticed that in the wizard and warlock spell lists there are a couple of spells that happen to have a duplicate (the thing they all seem to have in common is that they are all from unearthed arcanas)  
these are the ones i found:  
infestation  
toll the dead  
cause fear  
snare  
there might be others on the other complete spell lists but i haven't checked

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this. I'm assuming you are using the Character Sheet to generate the complete spell sheets and having this issue. I found why it is having a problem with spells that appear both in the UA and in XGtE, and [how to fix it](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/1df5682b5a3e2dc468a539c1dd85207545b48abb). This issue will be fixed in the next version :)
