### ISSUE TITLE
Duplicate spell entries when generating full spell sheets

### ISSUE THREAD

**Issue by LaytonGB** [morepurplemorebetter/MPMBs-Character-Record-Sheet#46]
Using only WotC and UA material. All duplicates are from UA: Starter Spells, and in my particular sheet (Sorcerer full spell list) this is limited to only Infestation and Chaos Bolt. This is on the sheet found in the dropbox, as of the current date 24/JAN/2018.
![image](https://user-images.githubusercontent.com/29107364/35316598-75218a84-00ca-11e8-8671-03dd6dee24b9.png)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting any issues you find with the sheet. The issue you are describing has already been fixed in the code in this repo, [see here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/1df5682b5a3e2dc468a539c1dd85207545b48abb). Thus, the next version of the sheet will no longer have this problem :)
