### ISSUE TITLE
Investigation and Medicine proficiency checkboxes linked

### ISSUE THREAD

**Issue by byamj** [morepurplemorebetter/MPMBs-Character-Record-Sheet#48]
When checking either the box for medicine or investigation proficiency, the other one fills in automatically. Same for unchecking.

**Comment by izulien** [comment]
I believe this was corrected before.  It is not in the current version I use.  Can you confirm which version and type of sheet you are seeing this on?

**Comment by morepurplemorebetter** [comment]
I can't find this issue with any of the 4 types of sheets (Printer Friendly, Printer Friendly-Redesign, Colourful A4, Colourful Letter), using v12.999 (or any other version for that matter). Can you please submit a link to the PDF with which you are having this issue? And describe on what page this is happening (front, companion, or wild shape), because there is not just one place that has a skills section.

Perhaps you imported some custom script?

I'm closing this issue for now, as it is something that is only affecting you, and not anybody else that downloads the latest version (v12.999) of the sheets.
