### ISSUE TITLE
Beast Master Ranger Companion HP is wrong

### ISSUE THREAD

**Issue by macarser** [morepurplemorebetter/MPMBs-Character-Record-Sheet#51]
I have a Beast Master Ranger who has a Companion page in his sheet. It is a tressym, a winged cat, and the companion's HP is calculated as either it's Hit Dice (species dependent) or four times the Ranger's level, whichever is higher.

When a sheet is opened, the companion's HP is being reset to the Hit Dice, when, in the case of this character's level, the four times the level is higher. So it's 20 when saved, but when closed and opened, back to 8.

Selecting the option to regenerate the companion pet does fix it, but again, it won't save it that way, and will reset back to just the Hit Dice total upon re-opening.

**Comment by morepurplemorebetter** [comment]
The fact that your companion's HP is changing automatically based on its HD is probably due to the fact that you set it to do that. When you click on the "Set Max HP" button on the companion page and go to the menu "Set the Max HP to automatically assume", which option is marked with a checkbox? If it isn't the last option "Don't change the maximum HP automatically", then the sheet will change the HP to the HD value every time it calculates anything (i.e. every time you change any field value). The HP derived from level is only added when you change a level, it isn't calculated every time something changes, because that's unnecessary.

I just tested this, and after making a ranger's companion and changing the level from 5 to 6, the HP of the Tressym went up from 20 to 24.

To fix you issue, change the "Set the Max HP" button's selection as described above and change the level of your character (or add the Tressym again as a Ranger's Companion). After doing that, you should see the HP being added correctly at level up/down.

I have changed the code to always automatically disable setting the HP to the HD value for ranger's companions at level up. This will be changed in the next version, [see here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/518fd6376ddb2714ab49ef89a1b0a4c468185be9).
