### ISSUE TITLE
"Borrow" speed, should be "burrow"

### ISSUE THREAD

**Issue by Smashman** [morepurplemorebetter/MPMBs-Character-Record-Sheet#52]
https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/b97019525406e178972bbdac67fcc3cb7a5d12ec/additional%20content%20syntax/Homebrew%20Syntax%20-%20RaceList.js#L38

Making some new race pages and I came across a reference to "borrow". Originally thinking this was just a typo in the docs, I found that "burrow" does not work in the object and it is indeed "borrow". This is incorrect, it should be "burrow".

**Comment by RobRoseKnows** [comment]
This is going to be a bitch to fix if there are other things referencing it. I'll take care of this.

**Comment by Smashman** [comment]
The sheet itself seems to only consider `borrow`, so I think that only Joost can fix it. 🙂

**Comment by RobRoseKnows** [comment]
Gah! Fu Adobe. Ah well, I've already changed most of the JavaScript, I'll submit a PR anyway.

**Comment by morepurplemorebetter** [comment]
Thank you for reporting this issue, a simple typo on my part! This has now been fixed with [this commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/96ba81fcd22c48f4ef0a72473c4498273a83343f) and [this commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/2371f96cbb60f1cdd83be5e4d8fa577f105444eb).

Thus, the next version of the sheet will use 'burrow' instead of 'borrow'.
