### ISSUE TITLE
UA Theurgist 

### ISSUE THREAD

**Issue by sainton** [morepurplemorebetter/MPMBs-Character-Record-Sheet#54]
The UA Theurgist as an Arcane Tradition for the Wizard is not coming into the character sheet as an option.

**Comment by morepurplemorebetter** [comment]
The problem with the Theurgy is in the RunFunctionAtEnd() function, which is broken in v12.999 of the sheet. The code has since been fixed [with this commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/a8123c40025d408fa1d8aae4583a0f1647f564cb), so the next version of the sheet won't have this issue.
