### ISSUE TITLE
Paladin prepared spells rounding up (should round down)

### ISSUE THREAD

**Issue by malaclypse1** [morepurplemorebetter/MPMBs-Character-Record-Sheet#57]
Paladins are getting their level/2 rounded up in prepared spells - PHB says it should be rounded down.

**Comment by morepurplemorebetter** [comment]
I am very certain that the sheet rounds the number of spells to prepare down. [This is the code for it](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_functions/FunctionsSpells.js#L540), and it uses [Math.floor()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/floor).

So I'm closing this issue. However, I'm happy to help you with your character sheet to see why it is doing what it is doing. Perhaps you added a modifier for spell preparation or forgot that it is also adding your ability modifier?

**Comment by malaclypse1** [comment]
I appreciate your time (and your great sheet). You can reproduce this bug by opening a new, unmodified sheet, selecting paladin as a class, and any odd level higher than 1. Create the spell sheet, select prepared spells only, and you get [this screenie](https://www.dropbox.com/s/2p8kzyo8xiodhua/Screenshot%202018-03-25%2009.54.27.png?dl=0)

If you generate a sheet with known spells, it shows spells to prepare correctly, so that implies the javascript dialog for generating a prepared spellsheet is where the error is. I think it might be [here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/_functions/FunctionsSpells.js#L2658) where you use ASround (and thus Math.round) to determine how many prepared spell dropdowns to show.

**Comment by morepurplemorebetter** [comment]
You are absolutely right! I didn't think of the selection dialog for prepared spells. It would have been helpful if you mentioned that in the initial description of the issue, but we got there :)

For some reason I assumed the calculated spellcasting level would be correct to use for the amount of spells to prepare, but that is incorrect, because the adjusted spellcasting level has to be rounded up, while the amount of spells to prepare has to be rounded down.

With 'adjusted spellcasting level' I mean the way the sheet takes the default spell slot progression and applies it to classes with 1/2 (paladin) or 1/3 (arcane trickster) spell progression. For those classes, the effective level is rounded up for some reason. Just compare the paladin spell slots per level with those of the wizard, and you'll see that a 7th level paladin has the same slot as a 4th level wizard.

Anyway, thank you very much for reporting this issue. I have fixed it with [this commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/4fab1c545507349db423933534262c64d2af1223), so it will be part of the next version of the sheet!
