### ISSUE TITLE
Updating Paladin stats does not update Saving Throws

### ISSUE THREAD

**Issue by DandD-gitstuff** [morepurplemorebetter/MPMBs-Character-Record-Sheet#58]
An Oath of Devotion paladin gets an ability starting at Lvl 6 that augments their saving throws by adding their Charisma modifier to all saves.  I'm seeing two buggy behaviors in 12.999 (using external "user" GitHub data imported from Feb 12, 2018)
1)  On a new sheet, create a paladin (Oath of Devotion)/Human with some set of stats for a 27-point buy.  Now, add 35000 XP to take the character to Lvl 8.  After the update to Lvl 8, increase Charisma to 20.  It should update Saving throws to include the +5 modifier, but does not.  If you add anything to the XP and update the XP, it will update the saving throws though.  But it's not doing it if you increase the stats immediately after the level upgrade.
2)  I have an old Paladin character from 12.86 sheet that was imported into 12.999.  It exhibits the same problem expressed in (1) above, BUT even when upgrading the character to Lvl 9, it does not update the Saving throws at all.  This file is attached to this report.
[Rothar Stronk.pdf](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/files/1864262/Rothar.Stronk.pdf)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting these issues.

1. This is resulting from the fact that the calculation order of the fields is not correct. The saving throws are calculated before the Charisma modifier is calculated, so changing the Charisma field will not update the saving throws. However, running the field calculations again will result in the correct value for everything. Whenever you change any field or open the sheet, these calculations are run again. So simply save the sheet and open it again will result in the right values. I will look into getting this calculation order fixed for the next version. This is not something that is visible in this repo, so I'm closing this issue.

2. The older sheets didn't have the option to add dynamic modifiers in the modifier field such as ability modifiers. Hence, the "to all Saves" modifier field is filled with a number (e.g. "4") in the older sheets while in the newer sheets it says "Cha". When importing a character from the older sheets these modifiers will overwrite anything added by the automation in the newer sheets and thus you will be stuck with the wrong thing. This is not something that I will be able to change. The solution is to either re-make the character in the new sheet or manually edit the modifier field to say "Cha" instead of a number.
