### ISSUE TITLE
Different typefaces on spell sheet

### ISSUE THREAD

**Issue by laovik489** [morepurplemorebetter/MPMBs-Character-Record-Sheet#59]
I noticed on the spell sheet it uses 2 different typefaces in certain places. Even if I change it from the default to tested one, it still shows up. 

It seems to be caused by inserting empty rows. 

![spell sheet](https://user-images.githubusercontent.com/38805289/39393070-33e84c38-4af3-11e8-8a72-00d6e3f26e45.JPG)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting any errors you find with the sheet!

It took me a bit of puzzling, but I figured out what you were trying to convey. Apparently, after changing the font of the sheet to something else then the default, inserted lines on the spell sheet can suddenly be set to using this non-default font. This happens for lines that are inserted above read-only lines (such as the headers and captions).

A change of font has no affect on the spell sheet lines, because they are made to fit one specific font and it would be counter-productive to have the user change the font (a lot of spell descriptions suddenly wouldn't fit).

So you are absolutely right, this behaviour is indeed not as intended and I found a way to fix it. I have found a way to fix the code so this won't happen again. This fix will be present in the next version of the sheet.

A temporary solution, for v12.999 and earlier, is to either never change the font, or to generate the spell sheet pages anew. That should reset all the fonts used to the default.
