### ISSUE TITLE
Wood Elf Race Don't Get Racial Treats

### ISSUE THREAD

**Issue by TheHungryOne** [morepurplemorebetter/MPMBs-Character-Record-Sheet#62]
Hi.
Thank you for your superb job on this PDF. I'm enjoying it a lot :)

Upon picking the race "Elf, Wood" in the drop down list, none of the racial treats are implemented.
All other Elf sub races work just fine.

Thanks :)

**Comment by morepurplemorebetter** [comment]
Thank you for reporting any issues you find with this sheet.

Note that this repo only contains the SRD content and thus only a single Elf subrace: the High Elf.

There exist a lot of fan-made scripts that you can import to add content to the sheets, including the Wood Elf. Perhaps that you are using one of those and that if you report it to the creator they can fix it. Or maybe it has already been fixed and you can just grab this newer import script.

I am closing this issue, because it is not encompassed within this repository.

**Comment by TheHungryOne** [comment]
I understand.
Thank you for clearing that up for me.
I'll look into it as you suggested :)
