### ISSUE TITLE
Sorcerer cantrip 'light' lists as Psionic

### ISSUE THREAD

**Issue by jstrobush** [morepurplemorebetter/MPMBs-Character-Record-Sheet#7]
Issue:  The Sorcerer cantrip 'light' gets listed as a psionic power.

Reproduction steps:
* Start with new sheet
* Set Cleric (War) 6 / Wild Mage Sorcerer 1
* Select the following sorcerer cantrips: Friends, Message, Minor Illusion, Light

Sheet version: v12.9, Printer Friendly Redesign

**Comment by morepurplemorebetter** [comment]
Wow, thank you so much for this very fast bug report!

I ran a quick test and this happens with all of 5 spells: "darkness", "fire storm", "light", "water breathing", and "whirlwind".

Now I'm a bit ashamed, because I should've checked for this. Guess I forgot with all the pressure to get the Mystic done!

[I have now fixed this.](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/581fac0576b7e6a46e91edcc715221cd6b174006)

I'll push out a new update immediately, to v12.91!
