### ISSUE TITLE
I think you are miss a Feature called Impenetrable Iron Tortoise Shell.

### ISSUE THREAD

**Issue by TheHangedGod** [morepurplemorebetter/MPMBs-Character-Record-Sheet#72]
https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/ef81f5a66ac0314953415fc43d1622d27cfeb186/additional%20content/Subclasses/Monk%20-%20Way%20of%20the%20Four%20Elements%2C%20Remastered%20%5BSpiketailDrake's%20work%2C%20transcribed%20by%20AKA_Sketch%20%26%20MPMB%5D.js#L281

**Comment by morepurplemorebetter** [comment]
That code was based on the PDF for version 2.0 from 2017/02/18. That PDF doesn't have anything in it by the name "Impenetrable iron Tortoise Shell". I see now that the document on Google Drive that the script links to has been updated since the version I used, but I don't know what has changed. I also see that the creators have continued development of the class and there are many more (newer) versions out there. From what I could gather, the latest version is 3.1 from 2017/03/31, and [can be found here](https://drive.google.com/file/d/0B5ttoyMfsaC7eFhVenpwZ0R4ZmM/view).

I'm currently swamped and don't have time to look through documents finding all the things that have changed and write a script for it. I don't intend to update only parts of a script. I feel it should be either update everything to another version, or nothing, so that at least the script is consistent with one version.

You are welcome to write your own script for a new version (utilizing this as a base if you want) and then both versions can live side-by-side as I've done for the Gunslinger subclass.
