### ISSUE TITLE
Adding custom scripts removes certain sources

### ISSUE THREAD

**Issue by aga9** [morepurplemorebetter/MPMBs-Character-Record-Sheet#74]
When adding custom scripts to the PDF, some sources are automatically removed, requiring them to be re-added manually.

To reproduce:

1. Create a new sheet.
2. Add some sources, including several UA sources.
3. Add a custom script: Functions > Add Extra Material > Add Material Manually (copy-paste)
4. You will be prompted to check the sources again. See that the UA sources have been removed.

**Comment by morepurplemorebetter** [comment]
Thank you very much for reporting any bugs you find with the sheet! And especially for making such a detailed walkthrough of how to reproduce the issue.

The issue you are describing is known and will be fixed in the next version of the sheet (v13). The fix is actually already included in this Git, as the code is for the latest beta of the sheet, v13.0.0beta6. This beta is available for supporters of [my Patreon](https://www.patreon.com/morepurplemorebetter), but once it is no longer in beta it will be available for everybody.
