### ISSUE TITLE
[Request] Calculating Equipment Weight

### ISSUE THREAD

**Issue by mouse0270** [morepurplemorebetter/MPMBs-Character-Record-Sheet#8]
I know a lot of DM's handle weight differently because it is just such an annoying thing to have the player's try to manage, especially if they are new to D&D. One of the ways I have managed to help players manage weight without making it increasingly difficulty was to make it so that the backpack, would just reduce their total carried weight by 30lbs.

We recently switched over to your amazing Character sheet because of the ease to use, however we realized that in the LB column of the Equipment section, we were not able to enter a negative number.

Would you consider making it so that the number entered in this column can be negative to help offset a players total carrying weight?

Our current solution for the time being was to disable the weight calculation for the first column, then add a gear item called (Additional Weight) and basically assign it to the total of column 1 - 30 lbs.

It isn't a perfect solution and neither is the ability to enter a negative  number, but they do allow us to not ignore the weight carried portion of the game well still keeping it pretty easy to manage.

**Comment by morepurplemorebetter** [comment]
I disabled adding negative weight for the logical reason that things can't have negative mass. It also has a practical reason as the code has a limit set for the amount of numbers that can be in those columns and allowing the "-" character would cause some errors. In other words, I would have to go over the code again to see how I should fix that.

What you can do, as a workaround, is to put all the 'backpack stuff' in one of the equipment columns and the other things, for which you do want to calculate weight, in the other column(s). Then you can set the weight calculation to exclude the column with the backpack stuff in it.
You can then even add a 30 lb 'backpack' in one of the columns that is being counted towards the total so that the total carried weight reflects your special ruling.

Or am I not understanding you correctly that you make everything in a backpack just weight a standard 30 lb, regardless of content? Do you actually mean that the item 'backpack' gives somebody the ability to carry 30 extra lb?
If that is the case, you can just set the # column to '-1' and the weight to '30' and you should be all good.

**Comment by mouse0270** [comment]
Basically we treat backpacks as a +30 to your total carrying weight. So yes that is the case.

I didn't realize by putting a negative 1 and setting the weight to 30 it would be like a 30lbs to your carry weight.

Is this stated anywhere. I read though a lot of comments and even the FAQ but I didn't see it. I might have just over looked it though.

**Comment by morepurplemorebetter** [comment]
The # column is used as a multiplier for the weight. So if you have 2 of the same item, you put a 2 there instead of doubling the weight (so you don't have to do the maths yourself). As those fields in the # column don't have fancy keystroke/format scripts running, you can enter anything you want there.

It won't add 30 lb to your maximum allowed weight, but it will just add -30 to the subtotal of the column, thus removing 30 lb from the total weight carried, if the column you do this in is included.

**Comment by mouse0270** [comment]
That makes sense. thanks
