### ISSUE TITLE
ReferenceError: ParseMagicItem is not defined

### ISSUE THREAD

**Issue by redraider23** [morepurplemorebetter/MPMBs-Character-Record-Sheet#84]

**Comment by morepurplemorebetter** [comment]
Can you please elaborate on this issue. From just the title I have no idea what the problem is. This is most likely caused by the import script you are using, but without more information I can't help.

Please provide information like the sheet type (Colourful, Printer Friendly), the full version number (v13.0.0beta11), and the custom scripts you have loaded

Please walk me through, starting from a freshly downloaded sheet, how to reproduce this issue.

**Comment by redraider23** [comment]
ok. sorry for the lack of information i have no idea how to code and thought the error name would be enough.
1. open "MPMB's Character Record Sheet (v12.999) [Printer Friendly - Redesign].pdf"
2. in the select source books window click on "get more" then "import a file with additional material"
3. click on "add file"
4. paste the URL "https://raw.githubusercontent.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/master/additional%20content/v13/Classes/Improved%20Artificer%20%5BXP%20to%20Level%203%2C%20transcribed%20by%20MPMB%5D.js" as the file name
5. click "open"
6. click "apply changes"

**Comment by morepurplemorebetter** [comment]
The script you are importing is meant for v13 of the sheet and won't work with earlier versions. You can tell from the fact that it is in the "v13" folder and has the lines

    Date:		2019-01-30 (sheet v13.0.0beta11)

and

    RequiredSheetVersion(13);
