### ISSUE TITLE
Beta13 - Racial AS Modifiers not autofilling

### ISSUE THREAD

**Issue by TheMountainThatRoars** [morepurplemorebetter/MPMBs-Character-Record-Sheet#85]
Selecting Firbolg as a race does not prompt the Javascript changes window, nor does it auto fill the ability score modifiers.

![image](https://user-images.githubusercontent.com/34113316/54628588-3e051080-4a4c-11e9-9d7e-1b34ad31ab54.png)

![image](https://user-images.githubusercontent.com/34113316/54628758-8cb2aa80-4a4c-11e9-92c9-5cda327f2d65.png)

**Comment by TheMountainThatRoars** [comment]
This also happens with Goliath and Centaur.

**Comment by morepurplemorebetter** [comment]
Thank you for reporting any issues you find with the betas.

There is a bug with all races that increase the carrying capacity (Powerful Build), which causes the race to error out and not all of its features being applied, the ability scores being one of them. This is fixed in commit 8781b4798c2ca34caeb4991deab5967f99778a8e and will no longer be an issue in the next beta.
