### ISSUE TITLE
Robe of the Archmagi Doesn't Update Spell Save DC

### ISSUE THREAD

**Issue by RobRoseKnows** [morepurplemorebetter/MPMBs-Character-Record-Sheet#91]
Not sure if this is just limited to Robe of the Archmagi, but it's the item I used. It updates the spell save DC on the spellsheet, but not on the first page's ability save DC. Not sure if this is deliberate or not, but thought I would bring it to your attention regardless.

**Comment by morepurplemorebetter** [comment]
I can assure you that this is intentional. The DC's presented on the first page are the 'Ability Save DC' and not the 'Spell Save DC'. If you would be multiclassing and have differente DCs keyed off the same ability, you wouldn't want them all to change because of a magic item, just because they are keyed of the same ability. Thus, the sheet only changes it in the appropriate sections.
